---

- name: validate vars
  include_tasks: tasks/variables.yml

- name: prerequisite
  include_tasks: "tasks/{{ ansible_os_family | lower }}-prerequisite.yml"

- name: install
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-install.yml"
  when: 
    - state|default('present') == 'present'
    - download | default('true') | bool

- name: clear temp folder
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-clear-temp.yml"
  when: clear_temp_folder | default('no') | bool
  
- name: track versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-track-versions.yml"
  when: 
    - state|default('present') == 'present'
    - deploy | default('true') | bool

- name: remove archived versions
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-remove-archived.yml"
  when: 
    - state|default('present') == 'present'
    - deploy | default('true') | bool

- name: uninstall
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-uninstall.yml"
  when: state|default('present') == 'absent'

- name: set-facts for next steps
  include_tasks: "tasks/{{ ansible_os_family | os_family_to_os_type }}-set-facts.yml"